language: java

jdk:
- oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: hekonsek-github
    token:
      secure: "fpVnMehtzJIe7E+YMBfrZDndK+wmEM7evq7rnQPlUUa0L7Bm1rsUYmEOI+Ej4Jg32N9gIngZNVJb+kdGJbLXQNtUy5wYN7T2ymo3lQiV1J5ABk3l8smLCioou51kpE44I7NglPARd95aLWvdhr7eAh/70c7oKM8DZUB8d8PDMeUuHTU7khD66BOT9c6dEvZEsJlATQK0e8Y/44ipAdPVemj2bzZVxZTrtAchmxmIfp5Kh8ln7qp10kD3IzY1Oef7eEMAarBob1qQKqs+S/jPGW4KiUZYud9ip+Es7PQoqhDTNs9KgJVL+Wro9HDM78qeIUMCh4qpm9FZtygGMrO8390wPPfIV/PEuUnhaKJTfmm2Kpzr68Bpwa+ZejEL7KMeWO6crGmQQRnhxJpxy46Nmfo+m5lOWCBB93yHyN2a0yb6f2msDAv6bBEohWddCoC9y0kAavSaVRROeRYT6Dwmh+eP+8BrAblWLGYIMB5ZjO1CbX6dqOVtN+M/maMBZLCkz44lRNkKUch5gg9Jf98a+d/Axp7wIisW2E+qS6RJ4D+3n5OH2zhYEOLlaqDpkGvriwyvuy4v4+HygOYxM9kCU+o24NqdC69R3lu+FKAoOVC333ViPFoiR2PE/AfeprjdeViNI5LnWpLQ2Ubl/hn0L3Y5CFC5ojSty5Zy/0B/gDo="

script:
  - mvn clean install sonar:sonar -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)